//local
GET http://localhost:3000/user
###
GET http://localhost:3000/user/698789858cbde3db2c837723

//create user
###
POST http://localhost:3000/user/ 
content-type: application/json

{
  "profile": {
    "firstName": "Alex",
    "lastName": "Smith",
    "age": 32,
    "heightCm": 178,
    "weightKg": 75
  },
  "experienceLevel": 3,
  "primaryGoal": "strength",
  "secondaryGoals": ["balance", "mobility"],
  "availableEquipment": ["bodyweight", "dumbbells"],
  "workoutDurationMinutes": 45,
  "contraindications": ["wrist_pain"],
  "activeInjuries": [
    {
      "joint": "shoulder",
      "side": "right",
      "severity": 2,
      "allowedLoad": 40,
      "notes": "Impingement; avoid overhead pressing"
    }
  ]
}

//update user
###
PUT http://localhost:3000/user/698789858cbde3db2c837723
Content-Type: application/json

{
  "profile": {
    "age": 33
  }
}

//delete user
###
DELETE http://localhost:3000/user/699a07c438077c6b88c5d9a0/
